default: &default
  access_key_id: "AKIAILPCY7EYYS6V3W7Q"
  secret_access_key: "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"
development:
  <<: *default
  cover_image_bucket: "cover_image_development"
  ckeditor_image_bucket: "ckeditor_image_development"
test:
  access_key_id: "test"
  secret_access_key: "test"
  cover_image_bucket: "cover_image_test"
  ckeditor_image_bucket: "ckeditor_image_test"
demo:
  <<: *default
  cover_image_bucket: "cover_image_demo"
  ckeditor_image_bucket: "ckeditor_image_demo"
production:
  <<: *default
  cover_image_bucket: "cover_image_production"
  ckeditor_image_bucket: "ckeditor_image_production"