default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: baraza_development

test:
  <<: *default
  database: baraza_test

production:
  <<: *default
  database: baraza_production
  url: <%= ENV['DATABASE_URL'] %>
  username: baraza
  password: <%= ENV['BARAZA_DATABASE_PASSWORD'] %>
