# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  port: 3306
  host: 127.0.0.1
  username: <%=ENV["DB_USERNAME"] %>
  password: <%=ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: baraza_development

test:
  <<: *default
  database: baraza_test

production:
  <<: *default
  database: baraza_production

demo:
  <<: *default
  database: baraza_demo

staging:
  <<: *default
  database: baraza_staging